# Generated by Django 5.2.7 on 2026-01-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Warbond',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Warbond')),
                        ('name_pt_br', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Warbond (PT-BR)')),
                        ('image', models.ImageField(blank=True, null=True, upload_to='warbonds/', verbose_name='Imagem do Warbond')),
                        ('creditos_ganhaveis', models.IntegerField(default=0, verbose_name='Créditos Ganháveis')),
                        ('custo_medalhas_todas_paginas', models.IntegerField(default=0, verbose_name='Custo em Medalhas (Todas as Páginas)')),
                        ('custo_medalhas_todos_itens', models.IntegerField(default=0, verbose_name='Custo em Medalhas (Todos os Itens)')),
                        ('quantidade_paginas', models.IntegerField(default=0, verbose_name='Quantidade de Páginas')),
                        ('custo_supercreditos', models.IntegerField(default=0, verbose_name='Custo em Supercréditos')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                    ],
                    options={
                        'verbose_name': 'Warbond',
                        'verbose_name_plural': 'Warbonds',
                        'ordering': ['name'],
                        'indexes': [models.Index(fields=['name'], name='warbonds_wa_name_c2bcf4_idx')],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE armory_battlepass RENAME TO warbonds_warbond",
                    reverse_sql="ALTER TABLE warbonds_warbond RENAME TO armory_battlepass"
                ),
            ],
        ),
    ]
