# Generated by Django 5.2.7 on 2026-01-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warbonds', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='warbond',
                    new_name='warbonds_wa_name_f4d0ba_idx',
                    old_name='warbonds_wa_name_c2bcf4_idx',
                ),
            ],
            database_operations=[
                # The actual index in DB is 'armory_batt_name_c2bcf4_idx'
                # We rename it to what Django Expects: 'warbonds_wa_name_f4d0ba_idx'
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS armory_batt_name_c2bcf4_idx RENAME TO warbonds_wa_name_f4d0ba_idx",
                    reverse_sql="ALTER INDEX IF EXISTS warbonds_wa_name_f4d0ba_idx RENAME TO armory_batt_name_c2bcf4_idx"
                ),
            ],
        ),
    ]
