# Generated by Django 5.2.7 on 2026-01-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warbonds', '0002_rename_warbonds_wa_name_c2bcf4_idx_warbonds_wa_name_f4d0ba_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('name_pt_br', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome (PT-BR)')),
                ('is_event', models.BooleanField(default=False, verbose_name='É Evento?')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Fonte de Aquisição',
                'verbose_name_plural': 'Fontes de Aquisição',
                'ordering': ['name'],
            },
        ),
    ]
