# Generated by Django 5.2.7 on 2026-01-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warbonds', '0003_acquisitionsource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisitionsource',
            options={'ordering': ['name'], 'verbose_name': 'Outros', 'verbose_name_plural': 'Outros'},
        ),
    ]
