# Generated by Django 5.2.7 on 2026-01-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warbonds', '0004_alter_acquisitionsource_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitionsource',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição (PT-BR)'),
        ),
    ]
