# Generated by Django 5.2.7 on 2026-01-21 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armory', '0013_delete_stratagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_pt_br', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (PT-BR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weaponry/', verbose_name='Image')),
                ('damage_value', models.IntegerField(default=0, verbose_name='Standard Damage')),
                ('damage_type', models.CharField(choices=[('acid', 'Acid Damage'), ('arc', 'Arc Damage'), ('ballistic', 'Ballistic Damage'), ('explosion', 'Explosion Damage'), ('fire', 'Fire Damage'), ('impact', 'Impact Damage'), ('laser', 'Continuous Laser'), ('melee', 'Melee Damage'), ('gas', 'Gas Damage')], default='ballistic', max_length=20, verbose_name='Damage Type')),
                ('max_penetration', models.IntegerField(choices=[(0, 'No Hitbox'), (1, 'Unarmored I'), (2, 'Unarmored II'), (3, 'Light'), (4, 'Medium'), (5, 'Heavy'), (6, 'Tank I'), (7, 'Tank II'), (8, 'Tank III'), (9, 'Tank IV'), (10, 'Tank V'), (11, 'Tank VI'), (12, 'Indestructible')], default=3, verbose_name='Max Penetration')),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacity')),
                ('recoil', models.IntegerField(default=0, verbose_name='Recoil')),
                ('fire_rate', models.IntegerField(default=0, verbose_name='Fire Rate (RPM)')),
                ('dps', models.IntegerField(default=0, verbose_name='DPS')),
                ('spare_mags', models.IntegerField(default=0, verbose_name='Spare Mags')),
                ('source', models.CharField(choices=[('store', 'Store'), ('pass', 'Pass'), ('other', 'Other')], default='store', max_length=20, verbose_name='Source')),
                ('cost', models.IntegerField(default=0, verbose_name='Cost')),
                ('weapon_type', models.CharField(choices=[('assault_rifle', 'Assault Rifle'), ('marksman_rifle', 'Marksman Rifle'), ('submachine_gun', 'Submachine Gun'), ('shotgun', 'Shotgun'), ('explosive', 'Explosive'), ('energy', 'Energy-Based'), ('special', 'Special')], max_length=20, verbose_name='Weapon Type')),
                ('warbond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weapons', to='armory.battlepass', verbose_name='Warbond')),
            ],
            options={
                'verbose_name': 'Primary Weapon',
                'verbose_name_plural': 'Primary Weapons',
            },
        ),
        migrations.CreateModel(
            name='SecondaryWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_pt_br', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (PT-BR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weaponry/', verbose_name='Image')),
                ('damage_value', models.IntegerField(default=0, verbose_name='Standard Damage')),
                ('damage_type', models.CharField(choices=[('acid', 'Acid Damage'), ('arc', 'Arc Damage'), ('ballistic', 'Ballistic Damage'), ('explosion', 'Explosion Damage'), ('fire', 'Fire Damage'), ('impact', 'Impact Damage'), ('laser', 'Continuous Laser'), ('melee', 'Melee Damage'), ('gas', 'Gas Damage')], default='ballistic', max_length=20, verbose_name='Damage Type')),
                ('max_penetration', models.IntegerField(choices=[(0, 'No Hitbox'), (1, 'Unarmored I'), (2, 'Unarmored II'), (3, 'Light'), (4, 'Medium'), (5, 'Heavy'), (6, 'Tank I'), (7, 'Tank II'), (8, 'Tank III'), (9, 'Tank IV'), (10, 'Tank V'), (11, 'Tank VI'), (12, 'Indestructible')], default=3, verbose_name='Max Penetration')),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacity')),
                ('recoil', models.IntegerField(default=0, verbose_name='Recoil')),
                ('fire_rate', models.IntegerField(default=0, verbose_name='Fire Rate (RPM)')),
                ('dps', models.IntegerField(default=0, verbose_name='DPS')),
                ('spare_mags', models.IntegerField(default=0, verbose_name='Spare Mags')),
                ('source', models.CharField(choices=[('store', 'Store'), ('pass', 'Pass'), ('other', 'Other')], default='store', max_length=20, verbose_name='Source')),
                ('cost', models.IntegerField(default=0, verbose_name='Cost')),
                ('weapon_type', models.CharField(choices=[('pistol', 'Pistol'), ('melee', 'Melee'), ('special', 'Special')], max_length=20, verbose_name='Weapon Type')),
                ('warbond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weapons', to='armory.battlepass', verbose_name='Warbond')),
            ],
            options={
                'verbose_name': 'Secondary Weapon',
                'verbose_name_plural': 'Secondary Weapons',
            },
        ),
        migrations.CreateModel(
            name='Throwable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_pt_br', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (PT-BR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weaponry/', verbose_name='Image')),
                ('damage_value', models.IntegerField(default=0, verbose_name='Standard Damage')),
                ('damage_type', models.CharField(choices=[('acid', 'Acid Damage'), ('arc', 'Arc Damage'), ('ballistic', 'Ballistic Damage'), ('explosion', 'Explosion Damage'), ('fire', 'Fire Damage'), ('impact', 'Impact Damage'), ('laser', 'Continuous Laser'), ('melee', 'Melee Damage'), ('gas', 'Gas Damage')], default='ballistic', max_length=20, verbose_name='Damage Type')),
                ('max_penetration', models.IntegerField(choices=[(0, 'No Hitbox'), (1, 'Unarmored I'), (2, 'Unarmored II'), (3, 'Light'), (4, 'Medium'), (5, 'Heavy'), (6, 'Tank I'), (7, 'Tank II'), (8, 'Tank III'), (9, 'Tank IV'), (10, 'Tank V'), (11, 'Tank VI'), (12, 'Indestructible')], default=3, verbose_name='Max Penetration')),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacity')),
                ('recoil', models.IntegerField(default=0, verbose_name='Recoil')),
                ('fire_rate', models.IntegerField(default=0, verbose_name='Fire Rate (RPM)')),
                ('dps', models.IntegerField(default=0, verbose_name='DPS')),
                ('spare_mags', models.IntegerField(default=0, verbose_name='Spare Mags')),
                ('source', models.CharField(choices=[('store', 'Store'), ('pass', 'Pass'), ('other', 'Other')], default='store', max_length=20, verbose_name='Source')),
                ('cost', models.IntegerField(default=0, verbose_name='Cost')),
                ('weapon_type', models.CharField(choices=[('standard', 'Standard'), ('special', 'Special')], max_length=20, verbose_name='Weapon Type')),
                ('warbond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weapons', to='armory.battlepass', verbose_name='Warbond')),
            ],
            options={
                'verbose_name': 'Throwable',
                'verbose_name_plural': 'Throwables',
            },
        ),
    ]
