# Generated by Django 5.2.7 on 2026-01-21 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrimaryWeaponRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('favorite', 'Favorito'), ('collection', 'Coleção'), ('wishlist', 'Lista de Desejo')], max_length=20, verbose_name='Tipo de Relação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='weaponry.primaryweapon', verbose_name='Arma Primária')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_weapon_relations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relação Usuário-Arma Primária',
                'verbose_name_plural': 'Relações Usuário-Arma Primária',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'relation_type'], name='weaponry_us_user_id_c8072b_idx'), models.Index(fields=['item', 'relation_type'], name='weaponry_us_item_id_236c73_idx')],
                'unique_together': {('user', 'item', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='UserSecondaryWeaponRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('favorite', 'Favorito'), ('collection', 'Coleção'), ('wishlist', 'Lista de Desejo')], max_length=20, verbose_name='Tipo de Relação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='weaponry.secondaryweapon', verbose_name='Arma Secundária')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_weapon_relations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relação Usuário-Arma Secundária',
                'verbose_name_plural': 'Relações Usuário-Arma Secundária',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'relation_type'], name='weaponry_us_user_id_7573fa_idx'), models.Index(fields=['item', 'relation_type'], name='weaponry_us_item_id_b13f0b_idx')],
                'unique_together': {('user', 'item', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='UserThrowableRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('favorite', 'Favorito'), ('collection', 'Coleção'), ('wishlist', 'Lista de Desejo')], max_length=20, verbose_name='Tipo de Relação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='weaponry.throwable', verbose_name='Arremessável')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throwable_relations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relação Usuário-Arremessável',
                'verbose_name_plural': 'Relações Usuário-Arremessável',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'relation_type'], name='weaponry_us_user_id_ca7a2d_idx'), models.Index(fields=['item', 'relation_type'], name='weaponry_us_item_id_b18def_idx')],
                'unique_together': {('user', 'item', 'relation_type')},
            },
        ),
    ]
