# Generated by Django 5.2.7 on 2026-01-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0002_userprimaryweaponrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryweapon',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='primaryweapon',
            name='dps',
        ),
        migrations.RemoveField(
            model_name='primaryweapon',
            name='fire_rate',
        ),
        migrations.RemoveField(
            model_name='primaryweapon',
            name='recoil',
        ),
        migrations.RemoveField(
            model_name='primaryweapon',
            name='spare_mags',
        ),
        migrations.RemoveField(
            model_name='primaryweapon',
            name='warbond',
        ),
        migrations.RemoveField(
            model_name='secondaryweapon',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='secondaryweapon',
            name='dps',
        ),
        migrations.RemoveField(
            model_name='secondaryweapon',
            name='fire_rate',
        ),
        migrations.RemoveField(
            model_name='secondaryweapon',
            name='recoil',
        ),
        migrations.RemoveField(
            model_name='secondaryweapon',
            name='spare_mags',
        ),
        migrations.RemoveField(
            model_name='secondaryweapon',
            name='warbond',
        ),
        migrations.RemoveField(
            model_name='throwable',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='throwable',
            name='dps',
        ),
        migrations.RemoveField(
            model_name='throwable',
            name='fire_rate',
        ),
        migrations.RemoveField(
            model_name='throwable',
            name='recoil',
        ),
        migrations.RemoveField(
            model_name='throwable',
            name='spare_mags',
        ),
        migrations.RemoveField(
            model_name='throwable',
            name='warbond',
        ),
    ]
