# Generated by Django 5.2.7 on 2026-01-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warbonds', '0003_acquisitionsource'),
        ('weaponry', '0003_remove_primaryweapon_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryweapon',
            name='acquisition_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbonds.acquisitionsource', verbose_name='Specific Acquisition Source'),
        ),
        migrations.AddField(
            model_name='secondaryweapon',
            name='acquisition_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbonds.acquisitionsource', verbose_name='Specific Acquisition Source'),
        ),
        migrations.AddField(
            model_name='throwable',
            name='acquisition_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbonds.acquisitionsource', verbose_name='Specific Acquisition Source'),
        ),
    ]
