# Generated by Django 5.2.7 on 2026-01-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warbonds', '0004_alter_acquisitionsource_options'),
        ('weaponry', '0004_primaryweapon_acquisition_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryweapon',
            name='warbond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbonds.warbond', verbose_name='Warbond'),
        ),
        migrations.AddField(
            model_name='secondaryweapon',
            name='warbond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbonds.warbond', verbose_name='Warbond'),
        ),
        migrations.AddField(
            model_name='throwable',
            name='warbond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbonds.warbond', verbose_name='Warbond'),
        ),
        migrations.AlterField(
            model_name='primaryweapon',
            name='source',
            field=models.CharField(choices=[('store', 'Store'), ('warbond', 'Warbond'), ('other', 'Other')], default='store', max_length=20, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='secondaryweapon',
            name='source',
            field=models.CharField(choices=[('store', 'Store'), ('warbond', 'Warbond'), ('other', 'Other')], default='store', max_length=20, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='throwable',
            name='source',
            field=models.CharField(choices=[('store', 'Store'), ('warbond', 'Warbond'), ('other', 'Other')], default='store', max_length=20, verbose_name='Source'),
        ),
    ]
