# Generated by Django 5.2.7 on 2026-01-25 20:54

from django.db import migrations

def update_source_pass_to_warbond(apps, schema_editor):
    PrimaryWeapon = apps.get_model('weaponry', 'PrimaryWeapon')
    SecondaryWeapon = apps.get_model('weaponry', 'SecondaryWeapon')
    Throwable = apps.get_model('weaponry', 'Throwable')

    PrimaryWeapon.objects.filter(source='pass').update(source='warbond')
    SecondaryWeapon.objects.filter(source='pass').update(source='warbond')
    Throwable.objects.filter(source='pass').update(source='warbond')

def reverse_update(apps, schema_editor):
    PrimaryWeapon = apps.get_model('weaponry', 'PrimaryWeapon')
    SecondaryWeapon = apps.get_model('weaponry', 'SecondaryWeapon')
    Throwable = apps.get_model('weaponry', 'Throwable')

    PrimaryWeapon.objects.filter(source='warbond').update(source='pass')
    SecondaryWeapon.objects.filter(source='warbond').update(source='pass')
    Throwable.objects.filter(source='warbond').update(source='pass')

class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0005_primaryweapon_warbond_secondaryweapon_warbond_and_more'),
    ]

    operations = [
        migrations.RunPython(update_source_pass_to_warbond, reverse_update),
    ]
