# Generated by Django 5.2.7 on 2026-01-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warbonds', '0004_alter_acquisitionsource_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_pt_br', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (PT-BR)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_pt_br', models.TextField(blank=True, verbose_name='Description (PT-BR)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='boosters/', verbose_name='Icon')),
                ('cost', models.IntegerField(default=0, verbose_name='Cost (Medals)')),
                ('warbond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boosters', to='warbonds.warbond', verbose_name='Warbond')),
            ],
            options={
                'verbose_name': 'Booster',
                'verbose_name_plural': 'Boosters',
                'ordering': ['name'],
            },
        ),
    ]
