# Generated by Django 5.2.7 on 2026-01-24 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booster',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Description (PT-BR)'),
        ),
    ]
