# Generated by Django 5.2.7 on 2026-01-26 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0002_booster_created_at_booster_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBoosterRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('favorite', 'Favorite'), ('collection', 'Collection'), ('wishlist', 'Wishlist')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='booster.booster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Booster Relation',
                'verbose_name_plural': 'User Booster Relations',
                'indexes': [models.Index(fields=['user', 'relation_type'], name='booster_use_user_id_f6be27_idx')],
                'unique_together': {('user', 'booster', 'relation_type')},
            },
        ),
    ]
