# Generated by Django 5.2.7 on 2026-01-21 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratagems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStratagemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('favorite', 'Favorito'), ('collection', 'Coleção'), ('wishlist', 'Lista de Desejo')], max_length=20, verbose_name='Tipo de Relação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('stratagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='stratagems.stratagem', verbose_name='Stratagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stratagem_relations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relação Usuário-Stratagem',
                'verbose_name_plural': 'Relações Usuário-Stratagem',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'relation_type'], name='stratagems__user_id_09667e_idx'), models.Index(fields=['stratagem', 'relation_type'], name='stratagems__stratag_0d3254_idx')],
                'unique_together': {('user', 'stratagem', 'relation_type')},
            },
        ),
    ]
