# Generated by Django 5.2.7 on 2026-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratagems', '0002_userstratagemrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagem',
            name='has_backpack',
            field=models.BooleanField(default=False, verbose_name='Has Backpack'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='is_tertiary_weapon',
            field=models.BooleanField(default=False, verbose_name='Is Tertiary Weapon'),
        ),
    ]
