# Generated by Django 5.2.7 on 2026-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratagems', '0003_stratagem_has_backpack_stratagem_is_tertiary_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagem',
            name='ammo_box_refill',
            field=models.IntegerField(default=0, verbose_name='Ammo Box Refill'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Capacity'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='damage_type',
            field=models.CharField(choices=[('acid', 'Acid Damage'), ('arc', 'Arc Damage'), ('ballistic', 'Ballistic Damage'), ('explosion', 'Explosion Damage'), ('fire', 'Fire Damage'), ('impact', 'Impact Damage'), ('laser', 'Continuous Laser'), ('melee', 'Melee Damage'), ('gas', 'Gas Damage')], default='ballistic', max_length=20, verbose_name='Damage Type'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='damage_value',
            field=models.IntegerField(default=0, verbose_name='Standard Damage'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='dps',
            field=models.IntegerField(default=0, verbose_name='DPS'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='fire_rate',
            field=models.IntegerField(default=0, verbose_name='Fire Rate (RPM)'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='max_penetration',
            field=models.IntegerField(choices=[(0, 'No Hitbox'), (1, 'Unarmored I'), (2, 'Unarmored II'), (3, 'Light'), (4, 'Medium'), (5, 'Heavy'), (6, 'Tank I'), (7, 'Tank II'), (8, 'Tank III'), (9, 'Tank IV'), (10, 'Tank V'), (11, 'Tank VI'), (12, 'Indestructible')], default=3, verbose_name='Max Penetration'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='spare_mags',
            field=models.IntegerField(default=0, verbose_name='Spare Mags'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='supply_box_refill',
            field=models.IntegerField(default=0, verbose_name='Supply Box Refill'),
        ),
    ]
