# Generated by Django 5.2.7 on 2026-01-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratagems', '0004_stratagem_ammo_box_refill_stratagem_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stratagem',
            name='ammo_box_refill',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='damage_type',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='damage_value',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='dps',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='fire_rate',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='max_penetration',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='spare_mags',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='supply_box_refill',
        ),
    ]
