# Generated by Django 5.2.7 on 2026-01-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratagems', '0005_remove_stratagem_ammo_box_refill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagem',
            name='is_mecha',
            field=models.BooleanField(default=False, verbose_name='Is Mecha'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='is_turret',
            field=models.BooleanField(default=False, verbose_name='Is Turret'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='is_vehicle',
            field=models.BooleanField(default=False, verbose_name='Is Vehicle'),
        ),
    ]
