# Generated by Django 5.2.7 on 2026-01-24 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratagems', '0006_stratagem_is_mecha_stratagem_is_turret_and_more'),
        ('warbonds', '0002_rename_warbonds_wa_name_c2bcf4_idx_warbonds_wa_name_f4d0ba_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagem',
            name='warbond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stratagems', to='warbonds.warbond', verbose_name='Warbond'),
        ),
    ]
