# Generated by Django 5.2.7 on 2025-10-20 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('category', models.CharField(choices=[('light', 'Leve'), ('medium', 'Médio'), ('heavy', 'Pesado')], max_length=10, verbose_name='Categoria')),
                ('image', models.ImageField(blank=True, null=True, upload_to='armors/', verbose_name='Imagem')),
                ('armor', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto')], max_length=10, verbose_name='Armadura')),
                ('speed', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto')], max_length=10, verbose_name='Velocidade')),
                ('stamina', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto')], max_length=10, verbose_name='Stamina')),
                ('cost', models.IntegerField(default=0, verbose_name='Custo')),
                ('source', models.CharField(max_length=255, verbose_name='Fonte de Aquisição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Armadura',
                'verbose_name_plural': 'Armaduras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='capes/', verbose_name='Imagem')),
                ('cost', models.IntegerField(default=0, verbose_name='Custo')),
                ('source', models.CharField(max_length=255, verbose_name='Fonte de Aquisição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capa',
                'verbose_name_plural': 'Capas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='armory_cape_name_1e7058_idx')],
            },
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='helmets/', verbose_name='Imagem')),
                ('cost', models.IntegerField(default=0, verbose_name='Custo')),
                ('source', models.CharField(max_length=255, verbose_name='Fonte de Aquisição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capacete',
                'verbose_name_plural': 'Capacetes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='armory_helm_name_8e3cac_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArmorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='armory.armor', verbose_name='Armadura')),
                ('cape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='armory.cape', verbose_name='Capa')),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='armory.helmet', verbose_name='Capacete')),
            ],
            options={
                'verbose_name': 'Set de Armadura',
                'verbose_name_plural': 'Sets de Armadura',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Passive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('effect', models.CharField(max_length=255, verbose_name='Efeito Prático')),
            ],
            options={
                'verbose_name': 'Passiva',
                'verbose_name_plural': 'Passivas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='armory_pass_name_abd497_idx')],
            },
        ),
        migrations.AddField(
            model_name='armor',
            name='passive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armors', to='armory.passive', verbose_name='Passiva'),
        ),
        migrations.AddIndex(
            model_name='armor',
            index=models.Index(fields=['name'], name='armory_armo_name_fef71d_idx'),
        ),
        migrations.AddIndex(
            model_name='armor',
            index=models.Index(fields=['category'], name='armory_armo_categor_eca181_idx'),
        ),
        migrations.AddIndex(
            model_name='armor',
            index=models.Index(fields=['passive'], name='armory_armo_passive_4aff1a_idx'),
        ),
    ]
