# Generated by Django 5.2.7 on 2025-10-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sets/', verbose_name='Imagem do Set'),
        ),
    ]
