# Generated by Django 5.2.7 on 2025-10-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0002_armorset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='source',
            field=models.CharField(choices=[('store', 'Loja'), ('pass', 'Passe')], default='store', max_length=10, verbose_name='Fonte de Aquisição'),
        ),
        migrations.AlterField(
            model_name='cape',
            name='source',
            field=models.CharField(choices=[('store', 'Loja'), ('pass', 'Passe')], default='store', max_length=10, verbose_name='Fonte de Aquisição'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='source',
            field=models.CharField(choices=[('store', 'Loja'), ('pass', 'Passe')], default='store', max_length=10, verbose_name='Fonte de Aquisição'),
        ),
    ]
