# Generated by Django 5.2.7 on 2025-10-31 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0004_alter_armor_fields_to_integer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArmorSetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('favorite', 'Favorito'), ('collection', 'Coleção'), ('wishlist', 'Lista de Desejo')], max_length=20, verbose_name='Tipo de Relação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('armor_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='armory.armorset', verbose_name='Set de Armadura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_set_relations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relação Usuário-Set',
                'verbose_name_plural': 'Relações Usuário-Set',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'relation_type'], name='armory_user_user_id_793b1d_idx'), models.Index(fields=['armor_set', 'relation_type'], name='armory_user_armor_s_632621_idx')],
                'unique_together': {('user', 'armor_set', 'relation_type')},
            },
        ),
    ]
