# Generated by Django 5.2.7 on 2025-10-31 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0005_userarmorsetrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Passe')),
                ('image', models.ImageField(blank=True, null=True, upload_to='passes/', verbose_name='Imagem do Passe')),
                ('creditos_ganhaveis', models.IntegerField(default=0, verbose_name='Créditos Ganháveis')),
                ('custo_medalhas_todas_paginas', models.IntegerField(default=0, verbose_name='Custo em Medalhas (Todas as Páginas)')),
                ('custo_medalhas_todos_itens', models.IntegerField(default=0, verbose_name='Custo em Medalhas (Todos os Itens)')),
                ('quantidade_paginas', models.IntegerField(default=0, verbose_name='Quantidade de Páginas')),
                ('custo_supercreditos', models.IntegerField(default=0, verbose_name='Custo em Supercréditos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Passe',
                'verbose_name_plural': 'Passes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='armory_batt_name_c2bcf4_idx')],
            },
        ),
        migrations.AddField(
            model_name='armor',
            name='pass_field',
            field=models.ForeignKey(blank=True, help_text="Passe específico se a fonte for 'pass'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armors', to='armory.battlepass', verbose_name='Passe'),
        ),
        migrations.AddField(
            model_name='cape',
            name='pass_field',
            field=models.ForeignKey(blank=True, help_text="Passe específico se a fonte for 'pass'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capes', to='armory.battlepass', verbose_name='Passe'),
        ),
        migrations.AddField(
            model_name='helmet',
            name='pass_field',
            field=models.ForeignKey(blank=True, help_text="Passe específico se a fonte for 'pass'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helmets', to='armory.battlepass', verbose_name='Passe'),
        ),
        migrations.AddIndex(
            model_name='armor',
            index=models.Index(fields=['source'], name='armory_armo_source_d521b2_idx'),
        ),
        migrations.AddIndex(
            model_name='armor',
            index=models.Index(fields=['pass_field'], name='armory_armo_pass_fi_f3bafb_idx'),
        ),
        migrations.AddIndex(
            model_name='cape',
            index=models.Index(fields=['source'], name='armory_cape_source_ae5087_idx'),
        ),
        migrations.AddIndex(
            model_name='cape',
            index=models.Index(fields=['pass_field'], name='armory_cape_pass_fi_85c0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='helmet',
            index=models.Index(fields=['source'], name='armory_helm_source_d35e93_idx'),
        ),
        migrations.AddIndex(
            model_name='helmet',
            index=models.Index(fields=['pass_field'], name='armory_helm_pass_fi_546af4_idx'),
        ),
    ]
