# Generated by Django 5.2.7 on 2025-11-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0009_update_source_field_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorset',
            name='cape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='armory.cape', verbose_name='Capa'),
        ),
    ]
