# Generated by Django 5.2.7 on 2026-01-21 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0010_alter_armorset_cape'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArmorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('favorite', 'Favorito'), ('collection', 'Coleção'), ('wishlist', 'Lista de Desejo')], max_length=20, verbose_name='Tipo de Relação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='armory.armor', verbose_name='Armadura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_relations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relação Usuário-Armadura',
                'verbose_name_plural': 'Relações Usuário-Armadura',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'relation_type'], name='armory_user_user_id_c0dc1a_idx'), models.Index(fields=['armor', 'relation_type'], name='armory_user_armor_i_ced621_idx')],
                'unique_together': {('user', 'armor', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='UserCapeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('favorite', 'Favorito'), ('collection', 'Coleção'), ('wishlist', 'Lista de Desejo')], max_length=20, verbose_name='Tipo de Relação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='armory.cape', verbose_name='Capa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cape_relations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relação Usuário-Capa',
                'verbose_name_plural': 'Relações Usuário-Capa',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'relation_type'], name='armory_user_user_id_aa974d_idx'), models.Index(fields=['cape', 'relation_type'], name='armory_user_cape_id_ad5a16_idx')],
                'unique_together': {('user', 'cape', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='UserHelmetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('favorite', 'Favorito'), ('collection', 'Coleção'), ('wishlist', 'Lista de Desejo')], max_length=20, verbose_name='Tipo de Relação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='armory.helmet', verbose_name='Capacete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helmet_relations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relação Usuário-Capacete',
                'verbose_name_plural': 'Relações Usuário-Capacete',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'relation_type'], name='armory_user_user_id_9c3295_idx'), models.Index(fields=['helmet', 'relation_type'], name='armory_user_helmet__337404_idx')],
                'unique_together': {('user', 'helmet', 'relation_type')},
            },
        ),
    ]
