# Generated by Django 5.2.7 on 2026-01-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0011_userarmorrelation_usercaperelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stratagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_pt_br', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (PT-BR)')),
                ('department', models.CharField(choices=[('patriotic_admin', 'Patriotic Administration Center'), ('orbital_cannons', 'Orbital Cannons'), ('hangar', 'Hangar'), ('bridge', 'Bridge'), ('engineering_bay', 'Engineering Bay'), ('robotics_workshop', 'Robotics Workshop'), ('warbonds', 'Warbonds')], max_length=50, verbose_name='Department')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='stratagems/', verbose_name='Icon')),
                ('codex', models.CharField(help_text='Format: UP, DOWN, LEFT, RIGHT (comma separated)', max_length=50, verbose_name='Stratagem Codes')),
                ('cooldown', models.IntegerField(default=0, verbose_name='Cooldown (seconds)')),
                ('cost', models.IntegerField(default=0, verbose_name='Cost')),
                ('unlock_level', models.IntegerField(default=0, verbose_name='Unlock Level')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_pt_br', models.TextField(blank=True, null=True, verbose_name='Description (PT-BR)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stratagem',
                'verbose_name_plural': 'Stratagems',
                'ordering': ['department', 'name'],
            },
        ),
    ]
