# Generated by Django 5.2.7 on 2026-01-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0012_stratagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stratagem',
        ),
    ]
