# Generated by Django 5.2.7 on 2026-01-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0013_delete_stratagem'),
        ('warbonds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helmet',
            name='pass_field',
            field=models.ForeignKey(blank=True, help_text="Passe específico se a fonte for 'pass'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helmets', to='warbonds.warbond', verbose_name='Passe'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='pass_field',
            field=models.ForeignKey(blank=True, help_text="Passe específico se a fonte for 'pass'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armors', to='warbonds.warbond', verbose_name='Passe'),
        ),
        migrations.AlterField(
            model_name='cape',
            name='pass_field',
            field=models.ForeignKey(blank=True, help_text="Passe específico se a fonte for 'pass'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capes', to='warbonds.warbond', verbose_name='Passe'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='BattlePass',
                ),
            ],
            database_operations=[],
        ),
    ]
