# Generated by Django 5.2.7 on 2026-01-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0014_alter_helmet_pass_field_alter_armor_pass_field_and_more'),
        ('warbonds', '0003_acquisitionsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='acquisition_source',
            field=models.ForeignKey(blank=True, help_text="Usado quando a fonte é 'Outros' ou para eventos específicos", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armors', to='warbonds.acquisitionsource', verbose_name='Fonte de Aquisição (Específica)'),
        ),
        migrations.AddField(
            model_name='cape',
            name='acquisition_source',
            field=models.ForeignKey(blank=True, help_text="Usado quando a fonte é 'Outros' ou para eventos específicos", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capes', to='warbonds.acquisitionsource', verbose_name='Fonte de Aquisição (Específica)'),
        ),
        migrations.AddField(
            model_name='helmet',
            name='acquisition_source',
            field=models.ForeignKey(blank=True, help_text="Usado quando a fonte é 'Outros' ou para eventos específicos", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helmets', to='warbonds.acquisitionsource', verbose_name='Fonte de Aquisição (Específica)'),
        ),
    ]
