# Generated by Django 5.2.7 on 2026-01-24 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0015_armor_acquisition_source_cape_acquisition_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Set')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_sets/', verbose_name='Imagem do Set')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.armor', verbose_name='Armadura')),
                ('cape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.cape', verbose_name='Capa')),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.helmet', verbose_name='Capacete')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_sets', to=settings.AUTH_USER_MODEL, verbose_name='Curtidas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sets', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
            ],
            options={
                'verbose_name': 'Set de Usuário',
                'verbose_name_plural': 'Sets de Usuário',
                'ordering': ['-created_at'],
            },
        ),
    ]
