# Generated by Django 5.2.7 on 2026-01-24 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0016_userset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userset',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_sets', to=settings.AUTH_USER_MODEL, verbose_name='Favoritos'),
        ),
    ]
