# Generated by Django 5.2.7 on 2026-01-26 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0017_userset_favorites'),
        ('booster', '0003_userboosterrelation'),
        ('stratagems', '0007_stratagem_warbond'),
        ('weaponry', '0006_update_source_pass_to_warbond'),
    ]

    operations = [
        migrations.AddField(
            model_name='userset',
            name='booster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booster.booster', verbose_name='Booster'),
        ),
        migrations.AddField(
            model_name='userset',
            name='primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weaponry.primaryweapon', verbose_name='Arma Primária'),
        ),
        migrations.AddField(
            model_name='userset',
            name='secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weaponry.secondaryweapon', verbose_name='Arma Secundária'),
        ),
        migrations.AddField(
            model_name='userset',
            name='stratagems',
            field=models.ManyToManyField(blank=True, to='stratagems.stratagem', verbose_name='Estratagemas'),
        ),
        migrations.AddField(
            model_name='userset',
            name='throwable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weaponry.throwable', verbose_name='Granada/Arremessável'),
        ),
    ]
