# Generated by Django 5.2.7 on 2026-01-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0018_userset_booster_userset_primary_userset_secondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userset',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição (Markdown)'),
        ),
    ]
