# Generated by Django 5.2.7 on 2025-10-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_used',
            field=models.BooleanField(default=False, help_text='Token de reset usado'),
        ),
    ]
